### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [ReinhardPrix/FreedroidClassic#34] opened 2018-11-10 22:57 UTC
- [x] Missing sounds (error at start)
- [x] FreedroidWorld reference (repository was removed)
- [x] Victory screen. Was it in Paradroid (Classic)?
- [x] Debian patches (fix "engeneering", for example)
- [ ] Level editor crashes after removing something
Is it still alive? What happened to original FreedroidClassic?

**Comment by ReinhardPrix** [comment] 2019-04-11 14:04
@ghost thanks for the comments, I've now fixed the missing sounds and obsolete text references.
Not quite sure I understood these
>     * [ ]  Victory screen. Was it in Paradroid (Classic)?

not sure, but we were not trying to 100% stick to the original in all respects.

>     * [x]  Debian patches (fix "engeneering", for example)

what 'Debian patches' are you referring to specifically? Where would I find these to backport them to this repo?

>     * [ ]  Level editor crashes after removing something
do you have a specific case to reproduce this? What do you mean by 'removing something'? After replacing some element by 'floor' I did not observe a crash.

>       Is it still alive? What happened to original FreedroidClassic?
Not sure what you mean, this *is* the original FreedroidClassic, just moved here from sourceforge, where development focused mostly on FreedroidRPG.

**Comment by freedroidfriend** [comment] 2019-10-07 15:11
A part of GitHub link is not visible.
Debian patches here: http://deb.debian.org/debian/pool/main/f/freedroid/freedroid_1.0.2+cvs040112-6.debian.tar.xz

**Comment by ReinhardPrix** [comment] 2020-02-22 11:04
Thanks, I've fixed the victory screen github link readability. Most Debian patches don't apply or are obsoleted anyway by upstream changes, so I think I'm pretty caught up now with the backports.

**Comment by ReinhardPrix** [comment] 2020-02-22 11:07
I can't reproduce the Level Editor bug, so I'm closing this for now.
I believe there's probably a number of bugs in the level editor still, but I'd need a more specific example to go after them.

**Closed by ReinhardPrix** 2020-02-22 11:07 UTC
Labels: bug
